# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generateExamPage.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1265, 842)
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(650, 210, 271, 51))
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(340, 210, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(100, 350, 521, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.previewButton = QtWidgets.QPushButton(Form)
        self.previewButton.setGeometry(QtCore.QRect(1020, 750, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.previewButton.setFont(font)
        self.previewButton.setObjectName("previewButton")
        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setGeometry(QtCore.QRect(40, 750, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(390, 0, 471, 161))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.numberEntry = QtWidgets.QLineEdit(Form)
        self.numberEntry.setGeometry(QtCore.QRect(650, 340, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.numberEntry.setFont(font)
        self.numberEntry.setText("")
        self.numberEntry.setObjectName("numberEntry")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(200, 490, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(650, 500, 201, 281))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.diffEasy = QtWidgets.QRadioButton(self.groupBox)
        self.diffEasy.setGeometry(QtCore.QRect(30, 10, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.diffEasy.setFont(font)
        self.diffEasy.setObjectName("diffEasy")
        self.diffMedium = QtWidgets.QRadioButton(self.groupBox)
        self.diffMedium.setGeometry(QtCore.QRect(30, 80, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.diffMedium.setFont(font)
        self.diffMedium.setObjectName("diffMedium")
        self.diffHard = QtWidgets.QRadioButton(self.groupBox)
        self.diffHard.setGeometry(QtCore.QRect(30, 150, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.diffHard.setFont(font)
        self.diffHard.setObjectName("diffHard")
        self.diffMixed = QtWidgets.QRadioButton(self.groupBox)
        self.diffMixed.setGeometry(QtCore.QRect(30, 220, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.diffMixed.setFont(font)
        self.diffMixed.setObjectName("diffMixed")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Select A Course ID:"))
        self.label_3.setText(_translate("Form", "Enter Number of Questions in Exam:"))
        self.previewButton.setText(_translate("Form", "Preview Exam"))
        self.backButton.setText(_translate("Form", "Back"))
        self.label.setText(_translate("Form", "Generate An Exam"))
        self.label_4.setText(_translate("Form", "Select Difficulity of Questions:"))
        self.diffEasy.setText(_translate("Form", "Easy"))
        self.diffMedium.setText(_translate("Form", "Medium"))
        self.diffHard.setText(_translate("Form", "Hard"))
        self.diffMixed.setText(_translate("Form", "Mixed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

