# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'headTeacherPage.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1262, 819)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(290, -20, 721, 161))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.firstLastLabel = QtWidgets.QLabel(Form)
        self.firstLastLabel.setGeometry(QtCore.QRect(410, 90, 441, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.firstLastLabel.setFont(font)
        self.firstLastLabel.setObjectName("firstLastLabel")
        self.logoutButton = QtWidgets.QPushButton(Form)
        self.logoutButton.setGeometry(QtCore.QRect(1060, 730, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logoutButton.setFont(font)
        self.logoutButton.setObjectName("logoutButton")
        self.qInboxLabel = QtWidgets.QLabel(Form)
        self.qInboxLabel.setGeometry(QtCore.QRect(110, 90, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qInboxLabel.setFont(font)
        self.qInboxLabel.setObjectName("qInboxLabel")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(110, 170, 1041, 551))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1039, 549))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.quesLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.quesLabel.setGeometry(QtCore.QRect(40, 10, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.quesLabel.setFont(font)
        self.quesLabel.setObjectName("quesLabel")
        self.displayQuesId = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.displayQuesId.setGeometry(QtCore.QRect(210, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.displayQuesId.setFont(font)
        self.displayQuesId.setObjectName("displayQuesId")
        self.courseIdLabe = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.courseIdLabe.setGeometry(QtCore.QRect(360, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.courseIdLabe.setFont(font)
        self.courseIdLabe.setObjectName("courseIdLabe")
        self.displayCourseId = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.displayCourseId.setGeometry(QtCore.QRect(510, 10, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.displayCourseId.setFont(font)
        self.displayCourseId.setObjectName("displayCourseId")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(40, 60, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.displayTeachName = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.displayTeachName.setGeometry(QtCore.QRect(310, 60, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.displayTeachName.setFont(font)
        self.displayTeachName.setObjectName("displayTeachName")
        self.viewButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.viewButton.setGeometry(QtCore.QRect(790, 20, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.viewButton.setFont(font)
        self.viewButton.setObjectName("viewButton")
        self.quesLabel.raise_()
        self.displayQuesId.raise_()
        self.courseIdLabe.raise_()
        self.displayCourseId.raise_()
        self.label_8.raise_()
        self.displayTeachName.raise_()
        self.viewButton.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Head Teacher\'s Home Page"))
        self.firstLastLabel.setText(_translate("Form", "display first and last name tgt"))
        self.logoutButton.setText(_translate("Form", "Log Out"))
        self.qInboxLabel.setText(_translate("Form", "Question Inbox:"))
        self.quesLabel.setText(_translate("Form", "Question ID:"))
        self.displayQuesId.setText(_translate("Form", "11111111"))
        self.courseIdLabe.setText(_translate("Form", "Course ID:"))
        self.displayCourseId.setText(_translate("Form", "MATHEMATICS10"))
        self.label_8.setText(_translate("Form", "Teacher Submitted:"))
        self.displayTeachName.setText(_translate("Form", "display first and last name"))
        self.viewButton.setText(_translate("Form", "View Question"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

