# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subYearInfoPage.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hisEntry(object):
    def setupUi(self, hisEntry):
        hisEntry.setObjectName("hisEntry")
        hisEntry.resize(1269, 825)
        self.label = QtWidgets.QLabel(hisEntry)
        self.label.setGeometry(QtCore.QRect(270, 20, 751, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.sciCheck = QtWidgets.QCheckBox(hisEntry)
        self.sciCheck.setGeometry(QtCore.QRect(820, 350, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sciCheck.setFont(font)
        self.sciCheck.setObjectName("sciCheck")
        self.mathCheck = QtWidgets.QCheckBox(hisEntry)
        self.mathCheck.setGeometry(QtCore.QRect(400, 550, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.mathCheck.setFont(font)
        self.mathCheck.setObjectName("mathCheck")
        self.hisCheck = QtWidgets.QCheckBox(hisEntry)
        self.hisCheck.setGeometry(QtCore.QRect(400, 450, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hisCheck.setFont(font)
        self.hisCheck.setObjectName("hisCheck")
        self.musicCheck = QtWidgets.QCheckBox(hisEntry)
        self.musicCheck.setGeometry(QtCore.QRect(400, 650, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.musicCheck.setFont(font)
        self.musicCheck.setObjectName("musicCheck")
        self.artCheck = QtWidgets.QCheckBox(hisEntry)
        self.artCheck.setGeometry(QtCore.QRect(20, 150, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.artCheck.setFont(font)
        self.artCheck.setObjectName("artCheck")
        self.thaiCheck = QtWidgets.QCheckBox(hisEntry)
        self.thaiCheck.setGeometry(QtCore.QRect(820, 550, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.thaiCheck.setFont(font)
        self.thaiCheck.setObjectName("thaiCheck")
        self.engCheck = QtWidgets.QCheckBox(hisEntry)
        self.engCheck.setGeometry(QtCore.QRect(400, 250, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.engCheck.setFont(font)
        self.engCheck.setObjectName("engCheck")
        self.peCheck = QtWidgets.QCheckBox(hisEntry)
        self.peCheck.setGeometry(QtCore.QRect(820, 150, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.peCheck.setFont(font)
        self.peCheck.setObjectName("peCheck")
        self.religionCheck = QtWidgets.QCheckBox(hisEntry)
        self.religionCheck.setGeometry(QtCore.QRect(820, 650, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.religionCheck.setFont(font)
        self.religionCheck.setObjectName("religionCheck")
        self.socialCheck = QtWidgets.QCheckBox(hisEntry)
        self.socialCheck.setGeometry(QtCore.QRect(820, 450, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.socialCheck.setFont(font)
        self.socialCheck.setObjectName("socialCheck")
        self.compCheck = QtWidgets.QCheckBox(hisEntry)
        self.compCheck.setGeometry(QtCore.QRect(20, 650, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.compCheck.setFont(font)
        self.compCheck.setObjectName("compCheck")
        self.geoCheck = QtWidgets.QCheckBox(hisEntry)
        self.geoCheck.setGeometry(QtCore.QRect(400, 350, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.geoCheck.setFont(font)
        self.geoCheck.setObjectName("geoCheck")
        self.bioCheck = QtWidgets.QCheckBox(hisEntry)
        self.bioCheck.setGeometry(QtCore.QRect(20, 350, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bioCheck.setFont(font)
        self.bioCheck.setObjectName("bioCheck")
        self.chemCheck = QtWidgets.QCheckBox(hisEntry)
        self.chemCheck.setGeometry(QtCore.QRect(20, 450, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chemCheck.setFont(font)
        self.chemCheck.setObjectName("chemCheck")
        self.physicCheck = QtWidgets.QCheckBox(hisEntry)
        self.physicCheck.setGeometry(QtCore.QRect(820, 250, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.physicCheck.setFont(font)
        self.physicCheck.setObjectName("physicCheck")
        self.dramaCheck = QtWidgets.QCheckBox(hisEntry)
        self.dramaCheck.setGeometry(QtCore.QRect(400, 150, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dramaCheck.setFont(font)
        self.dramaCheck.setObjectName("dramaCheck")
        self.bandCheck = QtWidgets.QCheckBox(hisEntry)
        self.bandCheck.setGeometry(QtCore.QRect(20, 250, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bandCheck.setFont(font)
        self.bandCheck.setObjectName("bandCheck")
        self.chiorCheck = QtWidgets.QCheckBox(hisEntry)
        self.chiorCheck.setGeometry(QtCore.QRect(20, 550, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.chiorCheck.setFont(font)
        self.chiorCheck.setObjectName("chiorCheck")
        self.artEntry = QtWidgets.QLineEdit(hisEntry)
        self.artEntry.setGeometry(QtCore.QRect(190, 160, 181, 41))
        self.artEntry.setObjectName("artEntry")
        self.bandEntry = QtWidgets.QLineEdit(hisEntry)
        self.bandEntry.setGeometry(QtCore.QRect(190, 260, 181, 41))
        self.bandEntry.setObjectName("bandEntry")
        self.bioEntry = QtWidgets.QLineEdit(hisEntry)
        self.bioEntry.setGeometry(QtCore.QRect(190, 360, 181, 41))
        self.bioEntry.setObjectName("bioEntry")
        self.chemEntry = QtWidgets.QLineEdit(hisEntry)
        self.chemEntry.setGeometry(QtCore.QRect(190, 460, 181, 41))
        self.chemEntry.setObjectName("chemEntry")
        self.choirEntry = QtWidgets.QLineEdit(hisEntry)
        self.choirEntry.setGeometry(QtCore.QRect(190, 560, 181, 41))
        self.choirEntry.setObjectName("choirEntry")
        self.compEntry = QtWidgets.QLineEdit(hisEntry)
        self.compEntry.setGeometry(QtCore.QRect(190, 660, 181, 41))
        self.compEntry.setObjectName("compEntry")
        self.dramaEntry = QtWidgets.QLineEdit(hisEntry)
        self.dramaEntry.setGeometry(QtCore.QRect(610, 160, 181, 41))
        self.dramaEntry.setObjectName("dramaEntry")
        self.engEntry = QtWidgets.QLineEdit(hisEntry)
        self.engEntry.setGeometry(QtCore.QRect(610, 260, 181, 41))
        self.engEntry.setObjectName("engEntry")
        self.geoEntry = QtWidgets.QLineEdit(hisEntry)
        self.geoEntry.setGeometry(QtCore.QRect(610, 360, 181, 41))
        self.geoEntry.setObjectName("geoEntry")
        self.lineEdit_10 = QtWidgets.QLineEdit(hisEntry)
        self.lineEdit_10.setGeometry(QtCore.QRect(610, 460, 181, 41))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.mathEntry = QtWidgets.QLineEdit(hisEntry)
        self.mathEntry.setGeometry(QtCore.QRect(610, 560, 181, 41))
        self.mathEntry.setObjectName("mathEntry")
        self.musicEntry = QtWidgets.QLineEdit(hisEntry)
        self.musicEntry.setGeometry(QtCore.QRect(610, 660, 181, 41))
        self.musicEntry.setObjectName("musicEntry")
        self.religionEntry = QtWidgets.QLineEdit(hisEntry)
        self.religionEntry.setGeometry(QtCore.QRect(1060, 660, 181, 41))
        self.religionEntry.setObjectName("religionEntry")
        self.thaiEntry = QtWidgets.QLineEdit(hisEntry)
        self.thaiEntry.setGeometry(QtCore.QRect(1060, 560, 181, 41))
        self.thaiEntry.setObjectName("thaiEntry")
        self.socialEntry = QtWidgets.QLineEdit(hisEntry)
        self.socialEntry.setGeometry(QtCore.QRect(1060, 460, 181, 41))
        self.socialEntry.setObjectName("socialEntry")
        self.sciEntry = QtWidgets.QLineEdit(hisEntry)
        self.sciEntry.setGeometry(QtCore.QRect(1060, 360, 181, 41))
        self.sciEntry.setObjectName("sciEntry")
        self.physicEntry = QtWidgets.QLineEdit(hisEntry)
        self.physicEntry.setGeometry(QtCore.QRect(1060, 260, 181, 41))
        self.physicEntry.setObjectName("physicEntry")
        self.peEntry = QtWidgets.QLineEdit(hisEntry)
        self.peEntry.setGeometry(QtCore.QRect(1060, 160, 181, 41))
        self.peEntry.setObjectName("peEntry")
        self.doneButton = QtWidgets.QPushButton(hisEntry)
        self.doneButton.setGeometry(QtCore.QRect(1100, 740, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.doneButton.setFont(font)
        self.doneButton.setObjectName("doneButton")

        self.retranslateUi(hisEntry)
        QtCore.QMetaObject.connectSlotsByName(hisEntry)

    def retranslateUi(self, hisEntry):
        _translate = QtCore.QCoreApplication.translate
        hisEntry.setWindowTitle(_translate("hisEntry", "Form"))
        self.label.setText(_translate("hisEntry", "Subject and Year Information"))
        self.sciCheck.setText(_translate("hisEntry", "Science"))
        self.mathCheck.setText(_translate("hisEntry", "Mathematics"))
        self.hisCheck.setText(_translate("hisEntry", "History"))
        self.musicCheck.setText(_translate("hisEntry", "Music"))
        self.artCheck.setText(_translate("hisEntry", "Art"))
        self.thaiCheck.setText(_translate("hisEntry", "Thai"))
        self.engCheck.setText(_translate("hisEntry", "English"))
        self.peCheck.setText(_translate("hisEntry", "P.E."))
        self.religionCheck.setText(_translate("hisEntry", "Religion Studies"))
        self.socialCheck.setText(_translate("hisEntry", "Social Studies"))
        self.compCheck.setText(_translate("hisEntry", "Computer "))
        self.geoCheck.setText(_translate("hisEntry", "Geography"))
        self.bioCheck.setText(_translate("hisEntry", "Biology"))
        self.chemCheck.setText(_translate("hisEntry", "Chemistry"))
        self.physicCheck.setText(_translate("hisEntry", "Physics"))
        self.dramaCheck.setText(_translate("hisEntry", "Drama"))
        self.bandCheck.setText(_translate("hisEntry", "Band"))
        self.chiorCheck.setText(_translate("hisEntry", "Choir"))
        self.doneButton.setText(_translate("hisEntry", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hisEntry = QtWidgets.QWidget()
    ui = Ui_hisEntry()
    ui.setupUi(hisEntry)
    hisEntry.show()
    sys.exit(app.exec_())

